### ISSUE TITLE
Open Firewall ports

### ISSUE THREAD

**Issue by NeumannCo** [demichele/install-hornet-1.5#1]
I really like this script. Especially providing the ready-to-use service-file is a pretty cool feature. Anyway, I would suggest to open the necessary firewall-ports (at least 15600) in the process. You could even make this an option by asking the user in the process.

I can do a PR if you like.

**Comment by demichele** [comment]
You are right. Usually the VPS I install nodes in have these ports open but I just included the rules updates for 8081 and 15600 to reflect the guide by @svenger87
